from measurements.fft import FFT

# 2012
# International Symposium on Power Electronics,
# Electrical Drives, Automation and Motion
# Electromagnetic Environment under Over Head
# Power Transmission lines 110-500 kV
# I.S. Okrainskaya*, A.I. Sidorov*, and S.P. Gladyshev**
# *   South Ural State University, Tel: +7 351 267 9449, okrainskaya@yandex.ru, (Russia)
# ** Michigan-Dearborn University, Tel: 313 359 9084, sgladyshev@yahoo.com, (USA)
# RMS

harmonic_500kv_under_line_nT = {
    1: 7531.2,
    2: 7.34,
    3: 57.78,
    4: 17.74,
    5: 124.44,
    6: 2.46,
    7: 51.98,
    8: 4.58,
    9: 16.56,
    10: 3.42,
    11: 44.86,
    12: 1.72,
    13: 8.99,
    14: 1.04,
    15: 4.44,
    16: 3.48,
    17: 13.72,
    18: 2.24,
    19: 8.18,
    20: 1.16
}
# print(FFT.calculate_thd_from_dict(harmonic_500kv_under_line_nT))

harmonic_500kV_nT = {
    1: 764.30,
    2: 12.69,
    3: 83.31,
    4: 21.33,
    5: 126.39,
    6: 4.84,
    7: 61.65,
    8: 5.22,
    9: 20.94,
    10: 3.75,
    11: 38.64,
    12: 2.16,
    13: 12.45,
    14: 1.07,
    15: 5.04,
    16: 3.16,
    17: 17.08,
    18: 2.62,
    19: 14.50,
    20: 1.38
}
# print(FFT.calculate_thd_from_dict(harmonic_500kV_nT))

harmonic_220kv_nT = {
    1: 1825.90,
    2: 6.46,
    3: 34.97,
    4: 9.32,
    5: 14.05,
    6: 3.71,
    7: 3.33,
    8: 1.97,
    9: 3.04,
    10: 2.30,
    11: 14.26,
    12: 2.19,
    13: 3.67,
    14: 1.70,
    15: 1.89,
    16: 1.86,
    17: 5.24,
    18: 1.52,
    19: 3.15,
    20: 1.25
}
# print(FFT.calculate_thd_from_dict(harmonic_220kv_nT))

harmonic_110kv_nT = {
    1: 969.77,
    2: 5.55,
    3: 10.38,
    4: 2.67,
    5: 24.55,
    6: 3.22,
    7: 2.55,
    8: 2.00,
    9: 1.04,
    10: 1.41,
    11: 30.50,
    12: 2.12,
    13: 10.67,
    14: 1.34,
    15: 1.54,
    16: 2.27,
    17: 5.28,
    18: 2.11,
    19: 15.61,
    20: 3.07
}
# print(FFT.calculate_thd_from_dict(harmonic_110kv_nT))

# The Influence of Harmonic Content on the RMS Value of
# Electromagnetic Fields Emitted by Overhead Power Lines
# Jozef Bendík *,† , Matej Cenký † andŽanetaEleschová
# Therefore, the harmonic spectrum of the current represents the maximum allowable har
# monic distortion defined by IEEE Std 519-2014 for HV OPLs with a maximum demand
# current of over 1000 A [16]. The calculated THD of the current is 37.1%
#  IEEE Std 519-2014 (Revision of IEEE Std 519-1992); IEEE Recommended Practice and Requirements for Harmonic Control in
# Electric Power Systems. IEEE: Piscataway, NJ, USA, 2014; pp. 1–29.
# two lines (2t) 110 kV
# 700A on phase, 1.8m above ground,
# B_1 [RMS] = 22,97 µT
# B with harmonics [RMS] = 24,38 µT
# THD_I = 37.1%
harmonics_110kV_700A_uT = {
    1: 22.97
}
harmonic_IEEE_max_current_distortion = {
    1: 1.0,
    2: 0.028,
    3: 0.15,
    4: 0.028,
    5: 0.15,
    6: 0.028,
    7: 0.15,
    8: 0.028,
    9: 0.15,
    10: 0.018,
    12: 0.018,
    14: 0.018,
    16: 0.016,
    18: 0.016,
    20: 0.016,
}
harmonic_110kV_700A_uT = {key: value*22.97 for key, value in harmonic_IEEE_max_current_distortion.items()}

# max magnetic field corresponding to polish norms


# MAGNETIC FIELD EVALUATION AROUND 400 KV UNDERGROUND POWER
# CABLE UNDER HARMONICS EFFECTS
# Houari BOUDJELLA 1, * , Ahmed N. E. I AYAD 1 , Tahar ROUIBAH 1, Benyekhlef LAROUCI 1 ,
# Thamer A. H ALGHAMDI 2 , Ahmed ALTHOBAITI 3 , Sherif S. M. GHONEIM 3 ,
# Abdelkader Si TAYEB 4
# underground cable
# 4 cases (THD_I)
# THD_I=2.8%
# THD_I=3.6%
# THD_I=4%
# THD_I=4.7%
# B_1 [RMS] = 217uT
harmonic_400kV_1_8kA_I = {
    1: 1.8e3,
    5: 32,
    7: 35,
    11: 21,
    13: 10
}
harmonic_400kV_1_8kA_II = {
    1: 1.8e3,
    5: 48,
    7: 35,
    11: 22,
    13: 20
}
harmonic_400kV_1_8kA_III = {
    1: 1.8e3,
    5: 52,
    7: 37,
    11: 27,
    13: 23
}
harmonic_400kV_1_8kA_IV = {
    1: 1.8e3,
    5: 60,
    7: 42,
    11: 33,
    13: 32
}
# print(FFT.calculate_thd_from_dict(harmonic_400kV_1_8kA_I))
# print(FFT.calculate_thd_from_dict(harmonic_400kV_1_8kA_II))
# print(FFT.calculate_thd_from_dict(harmonic_400kV_1_8kA_III))
# print(FFT.calculate_thd_from_dict(harmonic_400kV_1_8kA_IV))

# Calculation of Magnetic Flux Density Harmonics in the Vicinity
# of Overhead Lines
# Adnan Mujezinovi´c * , Emir Turajli´c
# , Ajdin Alihodži´c
# , Maja Mufti´c Dedovi´c andNedisDautbaši´
# B=1.67 uT
# B=1.91uT
harmonic_typical_values = {
    1: 1.0,
    5: 0.2,
    7: 0.143,
    11: 0.091,
    13: 0.077,
    17: 0.059,
    19: 0.053,
    23: 0.043,
    25: 0.04,
    29: 0.034,
    31: 0.032,
}
harmonic_10kV_170A = {key: value*1.67 for key, value in harmonic_typical_values.items()}
harmonic_35kV_300A = {key: value*1.91 for key, value in harmonic_typical_values.items()}

# print(FFT.calculate_thd_from_dict(harmonic_typical_values))

# Computation and analysis of the extremely low frequency electric and
# magnetic fields generated by two designs of 400 kV overhead transmission
# lines
# Eduard Lunca⁎, Silviu Ursache, Alexandru Salceanu
# Technical University of Iasi, Faculty of Electrical Engineering, 23 Prof. Dimitrie Mangeron Street, 700050 Iasi, Romania
harmonic_400kV_1kA_10m_uT = {
    1: 19.18
}
harmonic_400kV_1kA_13m_uT = {
    1: 13.39
}
harmonic_400kV_1kA_21m_uT = {
    1: 6.15
}
harmonic_400kV_2t_1kA_10m_uT = {
    1: 17.8
}
harmonic_400kV_2t_1kA_13m_uT = {
    1: 11.92
}
harmonic_400kV_2t_1kA_21m_uT = {
    1: 5.7
}
# h=13m, 100A, 1.19uT
# 350A, 4.17 uT
# 500A, 5.96 uT
# 700A, 8.35 uT


# Study on Overhead Transmission Line Magnetic
# Field Harmonics of VSC-HVDC
# Tian Wu, Bin Xiao, Kai Liu,Ting Liu, Yong Peng, Ziming Su, Pan Tang, Xinglie Lei
# China Electric Power Research Institute
# harmonic_VSC_HVDC_10kV_uT = {
#     1: 3.0,
#     2: 1.325,
#     5: 0.2033,
#     8: 0.22,
#     38: 1.146,
#     44: 0.187,
#     71: 1.062,
#     7: 0.135,
#     37: 5.522,
#     40: 0.216,
#     43: 0.106,
#     70: 5.166,
#     73: 0.189,
#     6: 0.561,
#     9: 0.096,
#     33: 20.402,
#     36: 0.581,
#     39: 0.536,
#     66: 19.065
# }
# harmonic_VSC_HVDC_110kV_uT


# harmonic_eaf_current = {
#     1: 100.0,
#     2: 7.7,
#     3: 5.8,
#     4: 2.5,
#     5: 4.2,
#     7: 3.1
# }


if __name__ == "__main__":
    import matplotlib.pyplot as plt


    def plot_harmonic_percentages(B1_value, harmonics_dict, THD, plot_name="Widmo harmonicznych"):
        """
        Plots the harmonic spectrum as a percentage of the given B1_value with a logarithmic Y-axis.

        Args:
            B1_value (float): The value of the fundamental harmonic.
            harmonics_dict (dict): Dictionary of harmonic orders and magnitudes.
            THD (float/str): Total Harmonic Distortion to display on the graph.
        """
        # Sort the dictionary keys to ensure the x-axis is in numerical order
        orders = sorted(harmonics_dict.keys())

        # Calculate the percentage for each harmonic relative to B1_value
        percentages = [(harmonics_dict[order] / B1_value) * 100 for order in orders]

        # Create the plot
        plt.figure(figsize=(12, 6))
        bars = plt.bar(orders, percentages, color='skyblue', edgecolor='black', zorder=3)

        # Set y-axis to logarithmic scale
        plt.yscale('log')

        # Formatting the graph
        plt.xlabel('Harmoniczna', fontsize=12)
        plt.ylabel('Wartość procentowa podstawowej harmonicznej [%]', fontsize=12)

        # Display THD in the title
        plt.title(f'{plot_name}\nTHD: {THD:.2f}%',
                  fontsize=14
                  # , fontweight='bold'
                  )

        plt.xticks(orders)
        # Use 'both' to show minor grid lines, which helps read log scales
        plt.grid(axis='y', linestyle='--', alpha=0.7, zorder=0, which='both')

        # Add percentage text labels on top of each bar
        for bar, p in zip(bars, percentages):
            # Multiply height by 1.1 to position text correctly above the bar on a log scale
            plt.text(bar.get_x() + bar.get_width() / 2, bar.get_height() * 1.1,
                     f'{p:.2f}%',
                     ha='center', va='bottom', fontsize=9, rotation=45)

        plt.tight_layout()
        plt.show()


    # --- Example Usage ---
    # harmonic_500kv_under_line_nT = {
    #     1: 7531.2, 2: 7.34, 3: 57.78, 4: 17.74, 5: 124.44, 6: 2.46, 7: 51.98,
    #     8: 4.58, 9: 16.56, 10: 3.42, 11: 44.86, 12: 1.72, 13: 8.99, 14: 1.04,
    #     15: 4.44, 16: 3.48, 17: 13.72, 18: 2.24, 19: 8.18, 20: 1.16
    # }

    # Example THD calculation (or you can pass the result from your FFT module directly)
    import math

    # thd_val = math.sqrt(sum((v) ** 2 for k, v in harmonic_500kv_under_line_nT.items() if k != 1)) / \
    #           harmonic_500kv_under_line_nT[1] * 100


    # Pass the calculated/known THD into the function
    # plot_harmonic_percentages(harmonic_500kv_under_line_nT[1], harmonic_500kv_under_line_nT, FFT.calculate_thd_from_dict(harmonic_500kV_nT),
    #                           plot_name="Rozkład harmonicznych pola magnetycznego dla linii 500 kV (pod linią)")
    plot_harmonic_percentages(harmonic_500kV_nT[1], harmonic_500kV_nT,
                              FFT.calculate_thd_from_dict(harmonic_500kV_nT),
                              plot_name="Rozkład harmonicznych pola magnetycznego dla linii 500 kV")
    plot_harmonic_percentages(harmonic_220kv_nT[1], harmonic_220kv_nT,
                              FFT.calculate_thd_from_dict(harmonic_220kv_nT),
                              plot_name="Rozkład harmonicznych pola magnetycznego dla linii 220 kV")
    plot_harmonic_percentages(harmonic_110kv_nT[1], harmonic_110kv_nT,
                              FFT.calculate_thd_from_dict(harmonic_110kv_nT),
                              plot_name="Rozkład harmonicznych pola magnetycznego dla linii 110 kV")


    plot_harmonic_percentages(harmonic_typical_values[1], harmonic_typical_values, FFT.calculate_thd_from_dict(harmonic_typical_values),
                              plot_name="Rozkład harmonicznych pola magnetycznego typowy")
    plot_harmonic_percentages(harmonic_400kV_1_8kA_IV[1], harmonic_400kV_1_8kA_IV,
                              FFT.calculate_thd_from_dict(harmonic_400kV_1_8kA_IV),
                              plot_name="Rozkład harmonicznych pola magnetycznego dla linii 400 kV")
    plot_harmonic_percentages(harmonic_IEEE_max_current_distortion[1], harmonic_IEEE_max_current_distortion,
                              FFT.calculate_thd_from_dict(harmonic_IEEE_max_current_distortion),
                              plot_name="Rozkład harmonicznych pola magnetycznego dla max IEEE")
